import {auth,db} from './firebase.js';import {signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';import {collection,getDocs,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,query,orderBy} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=id=>document.getElementById(id);let products=[];const adminUid='GJXt6XRE6hgPtAKeNyNjcnBbjsZ2';
$('loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value,$('password').value);$('loginMsg').textContent='';}catch(e){$('loginMsg').textContent='Login failed: '+e.message}};$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,user=>{if(user&&user.uid===adminUid){$('login').classList.add('hidden');$('panel').classList.remove('hidden');load()}else if(user){$('loginMsg').textContent='This account is not the admin account.';signOut(auth)}else{$('login').classList.remove('hidden');$('panel').classList.add('hidden')}});
async function load(){await loadProducts();await loadOrders()}
async function loadProducts(){const s=await getDocs(collection(db,'products'));products=s.docs.map(d=>({id:d.id,...d.data()}));$('pCount').textContent=products.length;$('productList').innerHTML=products.map(p=>`<div class="item"><div><img src="${p.image||'https://placehold.co/100'}"><b>${esc(p.name)}</b><div>₹${Number(p.price||0)} • Stock ${Number(p.stock||0)}</div></div><div class="actions"><button class="edit" onclick="editProduct('${p.id}')">Edit</button><button class="danger" onclick="deleteProduct('${p.id}')">Delete</button></div></div>`).join('')||'<p>No products.</p>'}
async function loadOrders(){try{const s=await getDocs(query(collection(db,'orders'),orderBy('createdAt','desc')));$('oCount').textContent=s.size;$('orders').innerHTML=s.docs.map(d=>{const o=d.data();return `<div class="order"><b>${esc(o.customerName||'')}</b> • ${esc(o.customerPhone||'')}<br>${esc(o.address||'')}<br><b>₹${Number(o.total||0).toLocaleString('en-IN')}</b> • ${esc(o.status||'pending')}<br><small>${(o.items||[]).map(i=>esc(i.name)+' × '+i.qty).join(', ')}</small></div>`}).join('')||'<p>No orders.</p>'}catch(e){$('orders').innerHTML='<p>Orders load nahi hue.</p>'}}
$('save').onclick=async()=>{const data={name:$('name').value.trim(),price:Number($('price').value),stock:Number($('stock').value),image:$('image').value.trim(),updatedAt:serverTimestamp()};if(!data.name)return $('msg').textContent='Product name required.';try{if($('pid').value)await updateDoc(doc(db,'products',$('pid').value),data);else await addDoc(collection(db,'products'),{...data,createdAt:serverTimestamp()});$('msg').textContent='Saved!';clearForm();loadProducts()}catch(e){$('msg').textContent='Save failed: '+e.message}};
$('clear').onclick=clearForm;function clearForm(){$('pid').value='';$('name').value='';$('price').value='';$('stock').value='';$('image').value='';}
window.editProduct=id=>{const p=products.find(x=>x.id===id);if(!p)return;$('pid').value=id;$('name').value=p.name||'';$('price').value=p.price||0;$('stock').value=p.stock||0;$('image').value=p.image||'';scrollTo(0,0)};window.deleteProduct=async id=>{if(!confirm('Delete product?'))return;await deleteDoc(doc(db,'products',id));loadProducts()};function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
