import {db} from './firebase.js';import {collection,getDocs,addDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
let products=[],cart=[];const $=id=>document.getElementById(id);
async function load(){try{const s=await getDocs(collection(db,'products'));products=s.docs.map(d=>({id:d.id,...d.data()}));render(products)}catch(e){$('products').innerHTML='<p>Products load nahi hue. Firebase connection/rules check karein.</p>';console.error(e)}}
function render(list){$('products').innerHTML=list.length?list.map(p=>`<article class="card"><img src="${p.image||'https://placehold.co/600x600?text=NARI+FASHION'}"><div class="cardBody"><h3>${esc(p.name||'Product')}</h3><div class="price">₹${Number(p.price||0).toLocaleString('en-IN')}</div><div class="stock">${Number(p.stock||0)>0?'In stock':'Out of stock'}</div><button class="add" ${Number(p.stock||0)<=0?'disabled':''} data-id="${p.id}">Add to Cart</button></div></article>`).join(''):'<p>No products added yet.</p>';document.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(b.dataset.id))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({...p,qty:1});drawCart()}
function drawCart(){$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartRow"><img src="${x.image||'https://placehold.co/100'}"><div><b>${esc(x.name)}</b><div>₹${Number(x.price).toLocaleString('en-IN')} × ${x.qty}</div><button onclick="removeItem('${x.id}')">Remove</button></div></div>`).join(''):'<p>Cart empty.</p>';if(cart.length)$('cartItems').insertAdjacentHTML('beforeend',`<div class="total">Total: ₹${cart.reduce((a,x)=>a+Number(x.price)*x.qty,0).toLocaleString('en-IN')}</div>`)}
window.removeItem=id=>{cart=cart.filter(x=>x.id!==id);drawCart()};$('cartBtn').onclick=()=>{$('cart').classList.remove('hidden');drawCart()};$('closeCart').onclick=()=>$('cart').classList.add('hidden');$('search').oninput=e=>{const q=e.target.value.toLowerCase();render(products.filter(p=>String(p.name||'').toLowerCase().includes(q)))};
$('placeOrder').onclick=async()=>{if(!cart.length)return $('orderMsg').textContent='Cart empty hai.';const name=$('custName').value.trim(),phone=$('custPhone').value.trim(),address=$('custAddress').value.trim();if(!name||!phone||!address)return $('orderMsg').textContent='Name, mobile aur address bhariye.';try{const total=cart.reduce((a,x)=>a+Number(x.price)*x.qty,0);await addDoc(collection(db,'orders'),{customerName:name,customerPhone:phone,address,items:cart.map(x=>({productId:x.id,name:x.name,price:Number(x.price),qty:x.qty})),total,status:'pending',createdAt:serverTimestamp()});cart=[];drawCart();$('orderMsg').textContent='Order successfully place ho gaya!';}catch(e){console.error(e);$('orderMsg').textContent='Order place nahi hua. Firebase rules check karein.'}};load();
